### ISSUE TITLE
update() not working in updated 14 April 2018 Stretch image

### ISSUE THREAD

**Issue by ndward** [ev3dev/ev3dev-lang-python#457] opened 2018-04-20 21:44 UTC
In https://github.com/ev3dev/ev3dev/issues/1022 I reported that after installing the April 14 2018 EV3 Stretch image and updating it the 'brickd hyperactivity bug' has apparently been solved but two new problems have arisen: the update() command for the EV3 LCD display no longer works and the connection from Visual Studio Code to the EV3 via a USB cable is not stable beyond a maximum of a few hours. (When the connection is lost it is only lost for VS Code – there is still a connection between the computer and the EV3, which implies that the problem lies with the EV3 extension for VS Code.)

The error message I receive when update() fails resembles this:
```
Traceback (most recent call last):
  File "/home/robot/mine/printtext.py", line 7, in <module>
    lcd.update()
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 3325, in update
    raise Exception("Not supported")
Exception: Not supported
```

@dlech has stated in https://github.com/ev3dev/ev3dev/issues/1022 
`The updates include a major kernel upgrade from 4.9 to 4.14, so I suspect there will be multiple new issues related to this. … The 4.14.x kernel uses a new display driver. ev3dev-lang-python will need to be updated accordingly.`

Most of my scripts include update() and thus currently will not run with the latest (April 14 2018) version of the Stretch image. It would be great if this could be fixed!

**Comment by ddemidov** [comment] 2018-04-22 17:40
Duplicate of #455

**Closed as completed by ddemidov** 2018-04-22 17:40 UTC
