### ISSUE TITLE
Race condition in "wait()" causes call to block infinitely

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev-lang-python#583] opened 2018-12-20 02:20 UTC
- **ev3dev version:**

**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2018-07-15
Kernel version:     4.14.71-ev3dev-2.3.0-ev3
Brickman:           0.10.0
BogoMIPS:           148.88
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=00165340720B
BOARD_INFO_TYPE=main
```
- **ev3dev-lang-python version:** current `ev3dev-stretch` branch

From https://github.com/ev3dev/ev3dev/issues/1200.

When running a series of small movements where the motor will almost immediately reach the target, we sometimes hit a case where our wait logic gets stuck. This is improved by the re-ordering we did recently of the relevant wait code, but nonetheless still happens (in a slightly different way).

https://github.com/ev3dev/ev3dev-lang-python/blob/056f721c383a8a4331f7cc7f9958ffdcf794e573/ev3dev2/motor.py#L849-L874

From what I can tell, we get through the check on line 868 and determine we can't immediately return; so, we then call `poll` to block until something changes. In the time between when that happens and when the `poll` internals actually get around to checking, the `state` has been updated from `running` to `holding` and we've missed it. This causes the method to block indefinitely.

I don't see an obvious solution to this. We could add a timeout when waiting for the motor to stop (so it would at least not freeze). Alternately, perhaps we could modify the code where we call `poll` so that it always uses a small timeout so we manually check occasionally even if `poll` missed it. This latter approach would degrade responsiveness in the general case but improve the edge case.

**Comment by dlech** [comment] 2018-12-21 18:00
Off topic: `None if timeout is None else timeout` is no different than just `timeout`.

On topic: a timeout could always be passed to `poll()` even when the `timeout` argument is `None` to force checking the state again.

**Comment by strichter** [comment] 2019-01-09 02:31
This issue greatly limits the utility of the new library at this point, since any quick action will cause a deadlock.

I think the solution will be to pass the state upon original checking to the poll itself and instead of relying on the attribute access later on. I would add a line before 868 saying `state = self.state` and then pass `state` into the polling somehow. (I have not worked with this code at all yet.) That would completely eliminate the race condition without degrading performance.

BTW, how can one contribute patches for this project?

**Comment by WasabiFan** [comment] 2019-01-09 02:53
How often are you running into it, and with what version of this library?

The `poll` function is a wrapper around the Linux syscall of the same name, which just blocks until events are raised for the provided file descriptor then returns that event info. So the problem is that we are missing events... `poll` doesn't actually interact with the contents of the file, and therefore couldn't know whether the value has changed unless it receives a corresponding event.

We welcome pull requests if you'd like to contribute; it's often best to discuss the proposed changes in an issue first like you did here so we can plan it out before you put work into making the change.

**Comment by strichter** [comment] 2019-01-09 03:01
@WasabiFan If I increase the speed of my printer enough, I can reproduce it consistently. I am running on beta2 right now.

BTW, I looked more into how everything works and the fact that everything is done via simple I/O communication is super cool. I am getting more excited by the minute.

**Comment by strichter** [comment] 2019-01-09 03:23
Okay, here is another thought: You start polling in a thread before you check for the early exit. Once the check is complete you join the thread or kill it if the early exit condition is true.

BTW, I would not mind your idea about always polling with a timeout and only bail if the overall timeout is reached. I think the perf degredation would be minimal unless you have reason to believe that reading the state is expensive.

I assume inotify is not available, since we are stuck with the 2.3 kernel, right?

**Comment by ddemidov** [comment] 2019-01-09 07:04
Would something like this work?
```py
     def wait(self, cond, timeout=None):   
         tic = time.time() 
  
         if self._poll is None: 
             if self._state is None: 
                 self._state = self._attribute_file_open('state') 
             self._poll = select.poll() 
             self._poll.register(self._state, select.POLLPRI) 
  
         # --> Set poll timeout to something small
         poll_tm = min(timeout or 100, 100)

         while True:
             # --> This check is now done every poll_tm even if poll has nothing to report:
             if cond(self.state): 
                 return True 
  
             self._poll.poll(poll_tm)
  
             if timeout is not None and time.time() >= tic + timeout / 1000:
                 # --> final check when user timeout is reached
                 return cond(self.state) 
```

**Comment by strichter** [comment] 2019-01-09 14:20
@ddemidov This is exactly what I tried last night and my image printed completely (a 4 hour run where it used to hang within less than 30 secs). I had just hard-coded poll_tm to 10ms. It is also the solution that @WasabiFan suggested with the caveat that it has a small performance degradation.

In general I am a proponent for getting things to work *right* before getting things to *fast*. So +1 on the suggestion above. We might also consider the following algorithm to determine the poll timeout:

```
TM_MIN_IDLE_WAIT = 10  # in ms
TM_MAX_IDLE_WAIT = 100  # in ms
TM_NUM_IDLE_CHECKS = 20  # number of times to check for state change while polling
poll_tm = min(
    timeout/TM_NUM_IDLE_CHECKS if timeout is not None else TM_MAX_IDLE_WAIT, 
    TM_MAX_IDLE_WAIT)
poll_tm = max(TM_MIN_IDLE_WAIT, poll_tm)
```

This way the checks are always proportional to the given timeout and it is guaranteed that we check multiple times during an expected time scale. We then use the min and max idle time to either not overload the system with checks and polling restarts or to wait too long to detect a stuck situation. The latter is particularly important for cases where someone just specified a large timeout (many seconds or even minutes) as a fail-safe.

**Comment by ddemidov** [comment] 2019-01-09 18:04
We could also add third parameter with a reasonable default, e.g. `poll_tm=50`, so that users could modify it when necessary:
```py
def wait(self, cond, timeout=None, poll_tm=50):   
```

**Comment by WasabiFan** [comment] 2019-01-09 19:45
This seems reasonable to me. It would be nice to get some experimental data on how much slower this is — and, more importantly IMHO, how much less consistent it is.

Other note — this code has changed a bit since beta2. The check used to be after the poll call. So the existing unreleased (as of now) code in this repo is better than what has been released.

**Comment by strichter** [comment] 2019-01-09 23:34
@WasabiFan Given that `select` is a core, C implemented module, I assume that the overhead is minimal. If we really care about consistent performance, we need to make sure that Python does not switch to another thread while not polling. I think it switches threads every 10 byte calls or so. I wonder whether there is a way to say, do not switch while doing this work, then we could ensure that the behavior is extremely consistent or at least as good as it gets.

**Comment by strichter** [comment] 2019-01-09 23:36
@WasabiFan Do you have suggestions on how to test performance and consistency? (I am new here, so I do not know my way around everything yet.)

BTW, do you guys have a simulator for this library? That way you could test behavior without using the hardware. I am thinking simulating literally the hardware files.

**Comment by dwalton76** [comment] 2019-03-24 02:55
@strichter no simulator :( It has been discussed in the past ( #264 ) but no one has had the cycles/motivation to write one.

**Comment by dwalton76** [comment] 2019-03-24 03:01
> Would something like this work?
> 
> ```python
>      def wait(self, cond, timeout=None):   
>          tic = time.time() 
>   
>          if self._poll is None: 
>              if self._state is None: 
>                  self._state = self._attribute_file_open('state') 
>              self._poll = select.poll() 
>              self._poll.register(self._state, select.POLLPRI) 
>   
>          # --> Set poll timeout to something small
>          poll_tm = min(timeout or 100, 100)
> 
>          while True:
>              # --> This check is now done every poll_tm even if poll has nothing to report:
>              if cond(self.state): 
>                  return True 
>   
>              self._poll.poll(poll_tm)
>   
>              if timeout is not None and time.time() >= tic + timeout / 1000:
>                  # --> final check when user timeout is reached
>                  return cond(self.state) 
> ```

Couldn't we set ``poll_tm`` to zero after the first pass through the loop?  We only need to cover the scenario where the event already happened but we missed it so after we have checked for that once we should be able to go back to the normal polling method where we block until the state changes.

**Comment by WasabiFan** [comment] 2019-03-24 14:12
I don't have any data to back this up, but my guess is that it's possible to miss events every time we enter `poll`. If that's true, we always need to be checking whether our last call missed something.

**Comment by staadecker** [comment] 2019-04-20 13:40
Just to let everyone know that I was having this issue. Adding a 1 second delay between calls to the motors fixed it but it would be nice not to have to.

**Comment by dwalton76** [comment] 2019-04-20 15:37
@staadecker if I post a pull request can you test and verify the fix?

**Comment by staadecker** [comment] 2019-04-20 15:42
Yes I can try. My issue doesn't happen 100% of the time however. Any recommendations on how to get the new code. I'm unable to connect my EV3 to the internet (and therefore github) (see https://github.com/ev3dev/ev3dev/issues/1154).

**Comment by staadecker** [comment] 2019-04-20 17:51
Ok internet is up and running.

**Comment by dwalton76** [comment] 2019-04-21 02:03
@staadecker try this:
```
# ssh to your EV3 
$ cd ~/
$ git clone https://github.com/dwalton76/ev3dev-lang-python.git
$ cd ev3dev-lang-python
$ git checkout race-wait
$ export PYTHONPATH=/home/$USER/ev3dev-lang-python/
$ RUN_YOUR_PROGRAM.py
```

That will allow you to test the change in PR #622.  Let us know what you see.

Credit to @ddemidov for the patch

**Comment by staadecker** [comment] 2019-04-21 18:12
@dwalton76 . Unfortunately, when I tried to reproduce the issue, I could not (with the old code). So I can't test whether it fixes anything.

**Comment by dwalton76** [comment] 2019-05-10 22:37
I am about 99% sure I was able to reproduce this and verify the fix so am going to close this one

**Closed as completed by dwalton76** 2019-05-10 22:37 UTC
